JAVA=java
COMPILE=javac
SRC=./cn/hopefulme/jfortran//client/*.java

compile:$(SRC)
	$(COMPILE) $(SRC)

clean:
	rm ./cn/hopefulme/jfortran/client/*.class
	rm -f nohup.out

run:
	$(JAVA) cn.hopefulme.jfortran.client.Launcher
