JAVA=java
COMPILE=javac
SRC=./cn/hopefulme/jfortran/*.java

compile:$(SRC)
	$(COMPILE) $(SRC)

clean:
	rm -f ./cn/hopefulme/jfortran/*.class nohup.out temp/*

run:
	$(JAVA) cn.hopefulme.jfortran.Main
